# Generated by Django 2.1.15 on 2020-06-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('texto', models.CharField(max_length=400)),
                ('topico', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('colonia', models.CharField(max_length=50)),
                ('tipo_delito', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
            ],
        ),
    ]
