# Generated by Django 2.1.15 on 2020-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelitoAbierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Municipio', models.CharField(max_length=255)),
                ('Colonia', models.CharField(max_length=255)),
                ('TipoDelito', models.CharField(max_length=255)),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
            ],
        ),
    ]
